name: Simple Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test basic action
      run: echo "Hello World"
      
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test after checkout
      run: ls -la